### ISSUE TITLE
doesnt work in check_mk 1.2.8

### ISSUE THREAD

**Issue by FinalX92** [grtswt/check_mk#2]
i really like the whole map thing if u can can u make it work on 1.2.8?

Traceback (most recent call last):
File "/omd/sites/check/share/check_mk/web/htdocs/wato.py", line 254, in page_handler
modefunc("content")
File "/omd/sites/check/share/check_mk/web/htdocs/wato.py", line 15931, in <lambda>
"edit_host" : (["hosts"], lambda phase: mode_edit_host(phase, new=False, is_cluster=None)),
File "/omd/sites/check/share/check_mk/web/htdocs/wato.py", line 1312, in mode_edit_host
configure_attributes(new, {hostname: host}, "host", parent = Folder.current())
File "/omd/sites/check/share/check_mk/web/htdocs/wato.py", line 15819, in configure_attributes
attr.render_input(varprefix, defvalue)
TypeError: render_input() takes exactly 2 arguments (3 given)

this is the error code that shows when u want to add coordinates

kind regards FinalX

**Comment by grtswt** [comment]
It looks like an incompatible change in how render_input is called. Not sure how to make a plugin compatible with both 1.2.6 and 1.2.8.

**Comment by FinalX92** [comment]
is it posible to have it for 1.2.6 and also for 1.2.8??
2 diff files.

**Comment by grtswt** [comment]
I'll look into it.

**Comment by FinalX92** [comment]
Ty in advance

**Comment by FinalX92** [comment]
any progress?

**Comment by grtswt** [comment]
Not yet. Looking into overloading function calls to make it compatible with both version 1.2.6 and 1.2.8.

If you solve it, send me a patch and it will be quicker!

**Comment by FinalX92** [comment]
i havent solved it i cant script im a user XD
but ty for still checking into it

**Comment by FinalX92** [comment]
the 1.2.8 is the new stable 1.2.6 is old stable so i think doesnt need to work anymore for both just for 1.2.8

kind regards,
FinalX

**Comment by FinalX92** [comment]
any news yet?
